version: "3"

tasks:
  # Yellowpad Commands
  yellowpad:dev:
    desc: "Start both the FastAPI server and Next.js client concurrently."
    deps:
      - task: yellowpad:server:dev
      - task: yellowpad:client:dev

  yellowpad:client:dev:
    desc: "Start up the Nextjs development server with custom port"
    dir: app/web
    cmds:
      - pnpm dev -p 3001

  yellowpad:server:dev:
    desc: "Start the development FastAPI uvicorn server."
    dir: app/server
    cmds:
      - poetry run uvicorn main:app --reload

  yellowpad:server:test:
    desc: "Run the preestablished server tests for quality assurance (testing environment is under tests/)."
    dir: app/server
    cmds:
      - poetry run pytest -v

  leuchtturm:web:ui:
    desc: "Run the Inertia/React.js view for Leuchtturm's web chat application."
    dir: web
    cmds:
      - pnpm dev

  leuchtturm:web:server:
    desc: "Run the Laravel backend for Leuchtturm's web chat application"
    dir: web
    cmds:
      - php artisan serve
