# Project Information
[project]
name = "untitled-rag-system-api"
version = "0.1.0"
description = "FastAPI and shit"
# start command = pipx run poetry run uvicorn main:app --reload
authors = [
    { name = "migodbtc", email = "mjdmbunda@dbtcmandaluyong.one-bosco.org" },
]
requires-python = ">=3.11, <4.0"
dependencies = [
    "fastapi (>=0.136.1,<0.137.0)",
    "uvicorn (>=0.46.0,<0.47.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "langchain (>=1.2.18,<2.0.0)",
    "langchain-google-genai (>=4.2.2,<5.0.0)",
    "langchain-chroma (>=1.1.0,<2.0.0)",
]

# Poetry Configurations
[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
