import type { Notepad } from "./types";

// ─── Mock notepads ────────────────────────────────────────────────────────────

export const MOCK_NOTEPADS: Notepad[] = [
  {
    id: 1,
    user_id: 1,
    title: "Grocery List",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 1, notepad_id: 1, label: "Apples", checked: false, mode: "checkbox", flagged: false },
      { id: 2, notepad_id: 1, label: "Milk", checked: true, mode: "checkbox", flagged: false },
      { id: 3, notepad_id: 1, label: "Eggs", checked: false, mode: "checkbox", flagged: false },
      { id: 4, notepad_id: 1, label: "Spinach", checked: true, mode: "checkbox", flagged: false },
      { id: 5, notepad_id: 1, label: "Coffee beans", checked: false, flagged: true, mode: "checkbox" },
      { id: 6, notepad_id: 1, label: "Bread", checked: false, mode: "list", flagged: false },
    ],
  },
  {
    id: 2,
    user_id: 1,
    title: "Workout Plan",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 7,  notepad_id: 2, label: "Bench press 3×10", checked: true, mode: "checkbox", flagged: false },
      { id: 8,  notepad_id: 2, label: "Incline dumbbell 3×12", checked: true, mode: "checkbox", flagged: false },
      { id: 9,  notepad_id: 2, label: "Cable flyes 4×15", checked: false, mode: "checkbox", flagged: false },
      { id: 10, notepad_id: 2, label: "Tricep pushdowns 3×15", checked: false, mode: "checkbox", flagged: false },
      { id: 11, notepad_id: 2, label: "Overhead press 3×8", checked: false, flagged: true, mode: "checkbox" },
    ],
  },
  {
    id: 3,
    user_id: 1,
    title: "Reading List",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 12, notepad_id: 3, label: "Clean Code — Robert C. Martin", checked: true, mode: "list", flagged: false },
      { id: 13, notepad_id: 3, label: "The Pragmatic Programmer", checked: false, flagged: true, mode: "list" },
      { id: 14, notepad_id: 3, label: "Designing Data-Intensive Apps", checked: false, mode: "list", flagged: false },
      { id: 15, notepad_id: 3, label: "Atomic Habits — James Clear", checked: false, mode: "list", flagged: false },
    ],
  },
  {
    id: 4,
    user_id: 1,
    title: "Sprint Tasks",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 16, notepad_id: 4, label: "Implement RAG pipeline", checked: true, mode: "checkbox", flagged: false },
      { id: 17, notepad_id: 4, label: "Write unit tests for embedder", checked: false, flagged: true, mode: "checkbox" },
      { id: 18, notepad_id: 4, label: "Update API docs", checked: false, mode: "checkbox", flagged: false },
      { id: 19, notepad_id: 4, label: "Review open PRs", checked: false, mode: "checkbox", flagged: false },
      { id: 20, notepad_id: 4, label: "Set up staging environment", checked: true, mode: "checkbox", flagged: false },
    ],
  },
  {
    id: 5,
    user_id: 1,
    title: "Home Errands",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 21, notepad_id: 5, label: "Pay electricity bill", checked: true, flagged: true, mode: "checkbox" },
      { id: 22, notepad_id: 5, label: "Fix leaking faucet", checked: false, mode: "checkbox", flagged: false },
      { id: 23, notepad_id: 5, label: "Clean the garage", checked: false, mode: "checkbox", flagged: false },
      { id: 24, notepad_id: 5, label: "Buy new lightbulbs", checked: true, mode: "checkbox", flagged: false },
    ],
  },
  {
    id: 6,
    user_id: 1,
    title: "Travel Prep",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 25, notepad_id: 6, label: "Book flight tickets", checked: true, mode: "checkbox", flagged: false },
      { id: 26, notepad_id: 6, label: "Reserve hotel", checked: true, mode: "checkbox", flagged: false },
      { id: 27, notepad_id: 6, label: "Charge camera batteries", checked: false, mode: "checkbox", flagged: false },
      { id: 28, notepad_id: 6, label: "Print travel itinerary", checked: false, flagged: true, mode: "list" },
      { id: 29, notepad_id: 6, label: "Pack bags", checked: false, mode: "list", flagged: false },
    ],
  },
  {
    id: 7,
    user_id: 1,
    title: "Music Practice",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 30, notepad_id: 7, label: "Scales — 15 min warm-up", checked: true, mode: "checkbox", flagged: false },
      { id: 31, notepad_id: 7, label: "Learn 'Clair de Lune' intro", checked: false, flagged: true, mode: "checkbox" },
      { id: 32, notepad_id: 7, label: "Sight-read new sheet music", checked: false, mode: "list", flagged: false },
      { id: 33, notepad_id: 7, label: "Record practice session", checked: false, mode: "list", flagged: false },
    ],
  },
  {
    id: 8,
    user_id: 1,
    title: "Study Goals",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 34, notepad_id: 8, label: "Review lecture notes — Ch. 5", checked: true, mode: "checkbox", flagged: false },
      { id: 35, notepad_id: 8, label: "Submit thesis outline", checked: false, flagged: true, mode: "checkbox" },
      { id: 36, notepad_id: 8, label: "Complete practice problems", checked: false, mode: "checkbox", flagged: false },
      { id: 37, notepad_id: 8, label: "Read journal articles (×3)", checked: false, mode: "list", flagged: false },
    ],
  },
  {
    id: 9,
    user_id: 1,
    title: "Side Project",
    created_at: "2026-05-17T06:00:00Z",
    updated_at: "2026-05-17T06:00:00Z",
    tasks: [
      { id: 38, notepad_id: 9, label: "Design database schema", checked: true, mode: "checkbox", flagged: false },
      { id: 39, notepad_id: 9, label: "Scaffold Next.js project", checked: true, mode: "checkbox", flagged: false },
      { id: 40, notepad_id: 9, label: "Build auth flow", checked: false, flagged: true, mode: "checkbox" },
      { id: 41, notepad_id: 9, label: "Write README", checked: false, mode: "list", flagged: false },
      { id: 42, notepad_id: 9, label: "Deploy to Vercel", checked: false, mode: "checkbox", flagged: false },
    ],
  },
];
